# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeuse',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_uses', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promocodeuse',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='marketing.promocode'),
        ),
        migrations.AddField(
            model_name='promocodeuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_uses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promocodeuse',
            index=models.Index(fields=['promo_code', 'user'], name='marketing_p_promo_c_b97d0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='promocodeuse',
            constraint=models.UniqueConstraint(fields=('promo_code', 'order'), name='unique_promo_per_order'),
        ),
    ]
