# Generated by Django 5.2.17 on 2026-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tag',
            field=models.CharField(blank=True, max_length=30, verbose_name='подпись над заголовком'),
        ),
    ]
