# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('composition', models.CharField(blank=True, max_length=500, verbose_name='состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True, verbose_name='в наличии')),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.product')),
            ],
            options={
                'verbose_name': 'фото товара',
                'verbose_name_plural': 'фото товаров',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='юр. название')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='телефон')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address_text', models.CharField(max_length=255, verbose_name='адрес')),
                ('logo', models.ImageField(blank=True, upload_to='shops/logos/')),
                ('cover_photo', models.ImageField(blank=True, upload_to='shops/covers/')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('suspended', 'Приостановлен')], db_index=True, default='pending', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='комиссия платформы, %')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='мин. сумма заказа')),
                ('card_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена открытки (0 = бесплатно)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(blank=True, related_name='shops', to='core.deliveryzone', verbose_name='зоны доставки')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.shop'),
        ),
        migrations.CreateModel(
            name='ShopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер')], default='manager', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='catalog.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сотрудник магазина',
                'verbose_name_plural': 'сотрудники магазинов',
            },
        ),
        migrations.CreateModel(
            name='ShopWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='день недели')),
                ('open_time', models.TimeField(verbose_name='открытие')),
                ('close_time', models.TimeField(verbose_name='закрытие')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='выходной')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='catalog.shop')),
            ],
            options={
                'verbose_name': 'часы работы',
                'verbose_name_plural': 'часы работы',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_available', 'is_active'], name='catalog_pro_shop_id_dfadff_idx'),
        ),
        migrations.AddIndex(
            model_name='shopstaff',
            index=models.Index(fields=['shop'], name='catalog_sho_shop_id_6097c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopstaff',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_staff'),
        ),
        migrations.AddConstraint(
            model_name='shopworkinghours',
            constraint=models.UniqueConstraint(fields=('shop', 'weekday'), name='unique_shop_weekday'),
        ),
    ]
