# Generated by Django 5.2.17 on 2026-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='consecutive_timeouts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='таймаутов принятия подряд'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='скрыт из выдачи (авто-штраф)'),
        ),
    ]
