# Generated by Django 5.2.17 on 2026-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_shop_consecutive_timeouts_shop_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='наше фирменное'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_own',
            field=models.BooleanField(default=False, verbose_name='наш магазин (бренд платформы)'),
        ),
    ]
