# Generated by Django 5.2.17 on 2026-09-29 05:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_image_product_is_featured_shop_is_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Необязательно: если точка не выбрана на карте, в админке подставится центр Душанбе', null=True, srid=4326),
        ),
    ]
