# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='публичный номер')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('payment_failed', 'Ошибка оплаты'), ('expired', 'Истёк (не оплачен)'), ('paid', 'Оплачен'), ('shop_pending', 'Ждёт магазин'), ('accepted', 'Принят магазином'), ('rejected', 'Отклонён магазином'), ('timeout', 'Таймаут магазина'), ('preparing', 'Собирается'), ('ready', 'Готов'), ('courier_assigned', 'Курьер назначен'), ('picked_up', 'Забран курьером'), ('on_the_way', 'В пути'), ('arrived', 'Курьер на месте'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled_client', 'Отменён клиентом'), ('cancelled_shop', 'Отменён магазином'), ('cancelled_admin', 'Отменён платформой'), ('disputed', 'Спор')], db_index=True, default='created', max_length=20)),
                ('card_text', models.TextField(blank=True, verbose_name='текст открытки')),
                ('card_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=16)),
                ('delivery_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('delivery_address_text', models.CharField(max_length=255)),
                ('delivery_details', models.CharField(blank=True, max_length=255)),
                ('slot_type', models.CharField(choices=[('asap', 'Как можно скорее'), ('scheduled', 'Ко времени')], default='asap', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='комментарий клиента')),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.promocode')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.shop')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_photos/')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order')),
            ],
            options={
                'verbose_name': 'фото заказа',
                'verbose_name_plural': 'фото заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('payment_failed', 'Ошибка оплаты'), ('expired', 'Истёк (не оплачен)'), ('paid', 'Оплачен'), ('shop_pending', 'Ждёт магазин'), ('accepted', 'Принят магазином'), ('rejected', 'Отклонён магазином'), ('timeout', 'Таймаут магазина'), ('preparing', 'Собирается'), ('ready', 'Готов'), ('courier_assigned', 'Курьер назначен'), ('picked_up', 'Забран курьером'), ('on_the_way', 'В пути'), ('arrived', 'Курьер на месте'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled_client', 'Отменён клиентом'), ('cancelled_shop', 'Отменён магазином'), ('cancelled_admin', 'Отменён платформой'), ('disputed', 'Спор')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='null = система', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'история статуса',
                'verbose_name_plural': 'история статусов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client'], name='orders_orde_client__7a26db_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'status'], name='orders_orde_shop_id_2cc0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='orders_orde_order_i_f43086_idx'),
        ),
    ]
