# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'точка трека курьера',
                'verbose_name_plural': 'трек курьера',
            },
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offline', 'Не на линии'), ('online', 'На линии'), ('busy', 'На заказе')], db_index=True, default='offline', max_length=10)),
                ('current_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Последняя позиция; живые позиции дублируются в Redis', null=True, srid=4326)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль курьера',
                'verbose_name_plural': 'профили курьеров',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pin_code', models.CharField(max_length=6)),
                ('confirmation_type', models.CharField(choices=[('pin', 'PIN-код'), ('photo', 'Фото')], default='pin', max_length=10)),
                ('confirmation_photo', models.ImageField(blank=True, null=True, upload_to='delivery_confirmations/')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courierprofile')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'доставки',
            },
        ),
    ]
