# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='courierlocation',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='delivery.delivery'),
        ),
        migrations.AddIndex(
            model_name='courierlocation',
            index=models.Index(fields=['delivery'], name='delivery_co_deliver_562727_idx'),
        ),
    ]
