# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_review', 'На рассмотрении'), ('resolved_full_refund', 'Решён: полный возврат'), ('resolved_partial_refund', 'Решён: частичный возврат'), ('resolved_rejected', 'Решён: отказ')], db_index=True, default='open', max_length=30)),
                ('resolution_comment', models.CharField(blank=True, max_length=500)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'спор',
                'verbose_name_plural': 'споры',
                'ordering': ('-id',),
            },
        ),
    ]
