# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('alif', 'Алиф'), ('dc', 'Душанбе Сити'), ('stub', 'Тестовый контур (stub)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешен'), ('failed', 'Ошибка'), ('refunded', 'Возвращён'), ('partially_refunded', 'Частично возвращён')], db_index=True, default='pending', max_length=20)),
                ('provider_txn_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('shop', 'Магазин'), ('courier', 'Курьер')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('alif', 'Алиф'), ('dc', 'Душанбе Сити'), ('bank', 'Банк'), ('cash', 'Наличные')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Выплачена'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='delivery.courierprofile')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='catalog.shop')),
            ],
            options={
                'verbose_name': 'выплата',
                'verbose_name_plural': 'выплаты',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешен'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('provider_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='null = авто-возврат', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'verbose_name': 'возврат',
                'verbose_name_plural': 'возвраты',
            },
        ),
        migrations.CreateModel(
            name='ShopBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accrual', 'Начисление (+)'), ('commission', 'Комиссия (−)'), ('payout', 'Выплата (−)'), ('adjustment', 'Корректировка (±)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_transactions', to='catalog.shop')),
            ],
            options={
                'verbose_name': 'транзакция баланса магазина',
                'verbose_name_plural': 'баланс магазинов (ledger)',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='unique_successful_payment_per_order'),
        ),
        migrations.AddIndex(
            model_name='shopbalancetransaction',
            index=models.Index(fields=['shop'], name='payments_sh_shop_id_3ce1ff_idx'),
        ),
    ]
