# Generated by Django 5.2.17 on 2026-08-05 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='базовая стоимость')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='надбавка за км')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='мин. сумма заказа')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'зона доставки',
                'verbose_name_plural': 'зоны доставки',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='null = системное действие (Celery)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'аудит',
                'ordering': ('-created_at',),
            },
        ),
    ]
